name = "§lAziFy: Natural §3Ultra §r"
version = [0, 1, 0]
min_supported_mc_version = [1, 20, 80]
url = "https://youtube.com/@aziangelo"
authors = ["Azi Angelo"]
materials = ["Sky", "SunMoon", "RenderChunk", "Actor"]

[description]
# %w = patch warning, %v = version
long = '''
§c%w
§7- A Dynamic MCBE Shader!
%v
§3https://youtube.com/@aziangelo
'''
short = "A Shader Made For Good Use"

[uuid] # Use https://www.uuidgenerator.net/version4
header = "e54f2b6f-9a4d-4ab0-b446-11da6bf9a1f1"
module = "926192e4-15dd-420d-8563-37ef4402c7d4"

[info]
# %a = authors
copyright = '''
Copyright (c) %a

**Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited.
'''
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "BETA_AURORA"
materials = ["Sky"]
description = '''
[Beta] Aurora
'''

[[subpack]]
define = "VINTAGE_FILM_MODE"
materials = ["RenderChunk", "Sky", "Actor"]
description = '''
Vintage Film Mode
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
'''
