name: build

on:
  push:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/cache@v4
      with:
        key: env-files-win
        path: |
          ${{ github.workspace }}/env
          ${{ github.workspace }}/data
    - run: .\setup.bat
    - run: .\build.bat -m RenderChunk Sky SunMoon -p Windows
    - uses: actions/upload-artifact@v4
      with:
        name: Windows
        path: ./build/Windows
